version: "3"
services:
  offer-frontend:
    image: gabendocker/offer-frontend
    ports:
      - 3000:3000
    networks:
      - offer-network

  offer-backend:
    image: gabendocker/offer-backend
    depends_on:
      - mongodb
    environment:
      - DB_CONNECTION=${DB_CONNECTION}
      - SECRET=${SECRET}
    ports:
      - 4300:4300
    networks:
      - offer-network

  mongodb:
    image: mongo:4.4.6
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    networks:
      - offer-network

networks:
  offer-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
