name: Backend CI/CD

on:
  push:
    paths:
      - 'src/Backend/**'
    branches:
      - '**'
      - '!develop'
  pull_request:
    branches: [ develop, master ]
    types: [closed]
    paths:
      - 'src/Backend/**'

jobs:
  Backend-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Intall npm packages
      run: npm install --prefix src/Backend/
    - name: Running backend tests
      run: npm run test --prefix src/Backend/

  Build-and-Deploy-Backend:
    if: github.event.pull_request.merged == true
    needs: [Backend-test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push backend
        id: docker_build_backend
        uses: docker/build-push-action@v2
        with:
          context: src/Backend/
          file: src/Backend/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: gabendocker/offer-backend:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
